//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewStatus_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewStatus_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3Web.App_LocalResources.ViewStatus.aspx", typeof(ViewStatus_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancelResource1_Text {
            get {
                return ResourceManager.GetString("btnCancelResource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnCancelResource1_ToolTip {
            get {
                return ResourceManager.GetString("btnCancelResource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string btnSubmitResource1_Text {
            get {
                return ResourceManager.GetString("btnSubmitResource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnSubmitResource1_ToolTip {
            get {
                return ResourceManager.GetString("btnSubmitResource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to COLLABORATE from DRAFT.
        /// </summary>
        public static string CollaborateFromDraft {
            get {
                return ResourceManager.GetString("CollaborateFromDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to COLLABORATE from READY.
        /// </summary>
        public static string CollaborateFromReady {
            get {
                return ResourceManager.GetString("CollaborateFromReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to COLLABORATE from REVIEW.
        /// </summary>
        public static string CollaborateFromReview {
            get {
                return ResourceManager.GetString("CollaborateFromReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETE Item from OPEN.
        /// </summary>
        public static string CompleteItemFromOpen {
            get {
                return ResourceManager.GetString("CompleteItemFromOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create OPEN Item from COMPLETE.
        /// </summary>
        public static string CreateOpenFromComplete {
            get {
                return ResourceManager.GetString("CreateOpenFromComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to CURRENT from COLLABORATE.
        /// </summary>
        public static string CurrentFromCollaborate {
            get {
                return ResourceManager.GetString("CurrentFromCollaborate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to CURRENT from DRAFT.
        /// </summary>
        public static string CurrentFromDraft {
            get {
                return ResourceManager.GetString("CurrentFromDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to CURRENT from PENDING.
        /// </summary>
        public static string CurrentFromPending {
            get {
                return ResourceManager.GetString("CurrentFromPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to CURRENT from READY.
        /// </summary>
        public static string CurrentFromReady {
            get {
                return ResourceManager.GetString("CurrentFromReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to CURRENT from REVIEW.
        /// </summary>
        public static string CurrentFromReview {
            get {
                return ResourceManager.GetString("CurrentFromReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to DRAFT from COLLABORATE.
        /// </summary>
        public static string DraftFromCollaborate {
            get {
                return ResourceManager.GetString("DraftFromCollaborate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create DRAFT from CURRENT.
        /// </summary>
        public static string DraftFromCurrent {
            get {
                return ResourceManager.GetString("DraftFromCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create DRAFT from PENDING.
        /// </summary>
        public static string DraftFromPending {
            get {
                return ResourceManager.GetString("DraftFromPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to DRAFT from READY.
        /// </summary>
        public static string DraftFromReady {
            get {
                return ResourceManager.GetString("DraftFromReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to DRAFT from REVIEW.
        /// </summary>
        public static string DraftFromReview {
            get {
                return ResourceManager.GetString("DraftFromReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblVersionResource1_Text {
            get {
                return ResourceManager.GetString("lblVersionResource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblVersionResource1_ToolTip {
            get {
                return ResourceManager.GetString("lblVersionResource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paradigm 3 -- Change Item Status.
        /// </summary>
        public static string PageResource1_Title {
            get {
                return ResourceManager.GetString("PageResource1.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to PENDING from COLLABORATE.
        /// </summary>
        public static string PendingFromCollaborate {
            get {
                return ResourceManager.GetString("PendingFromCollaborate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to PENDING from DRAFT.
        /// </summary>
        public static string PendingFromDraft {
            get {
                return ResourceManager.GetString("PendingFromDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to PENDING from READY.
        /// </summary>
        public static string PendingFromReady {
            get {
                return ResourceManager.GetString("PendingFromReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to PENDING from REVIEW.
        /// </summary>
        public static string PendingFromReview {
            get {
                return ResourceManager.GetString("PendingFromReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Item Status.
        /// </summary>
        public static string pnlStatusTitle {
            get {
                return ResourceManager.GetString("pnlStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Version.
        /// </summary>
        public static string pnlStatusVersion {
            get {
                return ResourceManager.GetString("pnlStatusVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string rbStatusResource1_ToolTip {
            get {
                return ResourceManager.GetString("rbStatusResource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to READY from COLLABORATE.
        /// </summary>
        public static string ReadyFromCollaborate {
            get {
                return ResourceManager.GetString("ReadyFromCollaborate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to READY from DRAFT.
        /// </summary>
        public static string ReadyFromDraft {
            get {
                return ResourceManager.GetString("ReadyFromDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to READY from REVIEW.
        /// </summary>
        public static string ReadyFromReview {
            get {
                return ResourceManager.GetString("ReadyFromReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to REVIEW from COLLABORATE.
        /// </summary>
        public static string ReviewFromCollaborate {
            get {
                return ResourceManager.GetString("ReviewFromCollaborate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to REVIEW from DRAFT.
        /// </summary>
        public static string ReviewFromDraft {
            get {
                return ResourceManager.GetString("ReviewFromDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to REVIEW from READY.
        /// </summary>
        public static string ReviewFromReady {
            get {
                return ResourceManager.GetString("ReviewFromReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your SSO session has timed out. Please restart your browser have your application access restored..
        /// </summary>
        public static string SessionTimeout {
            get {
                return ResourceManager.GetString("SessionTimeout", resourceCulture);
            }
        }
    }
}
